
CREATE TABLE TBL_TERM(
	TERM_NUM VARCHAR2(10),
	BIS_NUM VARCHAR2(10),
	TERM_OPEN_DATE VARCHAR2(8),
	TERM_CLOSE_DATE VARCHAR2(8),
	TERM_STATUS VARCHAR2(2) DEFAULT '01' NOT NULL,
	CONSTRAINT TBL_TERM_PK PRIMARY KEY(TERM_NUM)
);                                        

ALTER TABLE TBL_TERM
MODIFY (TERM_STATUS VARCHAR2(2) DEFAULT '01' NOT NULL);
                          
DROP TABLE TBL_TERM;

select * from TBL_TERM ORDER BY TERM_NUM;          

UPDATE TBL_TERM SET TERM_STATUS = '02' WHERE TERM_CLOSE_DATE = 20240111;

COMMIT

INSERT INTO TBL_TERM(TERM_NUM,BIS_NUM, TERM_OPEN_DATE, TERM_CLOSE_DATE, TERM_STATUS)
VALUES('7000000007', '7777777777','20230102', '', DEFAULT);

INSERT INTO TBL_TERM(TERM_NUM,BIS_NUM,  TERM_OPEN_DATE, TERM_CLOSE_DATE, TERM_STATUS)
VALUES('8112101328', '8853588888', '20220102', '', DEFAULT);

INSERT INTO TBL_TERM(TERM_NUM,BIS_NUM, TERM_OPEN_DATE, TERM_CLOSE_DATE, TERM_STATUS)
VALUES('9000000009', '9999999999', '20230103', '20240111', '02');

select * from TBL_TERM WHERE TERM_NUM = '7000000001';
COMMIT;

DELETE FROM TBL_CARD_BIN WHERE CARD_DIF = 'QQC';

CREATE TABLE TBL_CARD_BIN(
	CARD_BIN VARCHAR2(8)NOT NULL,
	CARD_DIF VARCHAR2(3)NOT NULL,
	CARD_STATUS VARCHAR2(2) DEFAULT '01' NOT NULL,
	CONSTRAINT TBL_CARD_BIN_PK PRIMARY KEY(CARD_BIN)
	);         

INSERT INTO TBL_CARD_BIN(CARD_BIN,CARD_DIF, CARD_STATUS)
VALUES('91234567', 'KBC',DEFAULT);
INSERT INTO TBL_CARD_BIN(CARD_BIN,CARD_DIF, CARD_STATUS)
VALUES('98888888', 'BCC',DEFAULT);
INSERT INTO TBL_CARD_BIN(CARD_BIN,CARD_DIF, CARD_STATUS)
VALUES('966666', 'SSC',DEFAULT);            
INSERT INTO TBL_CARD_BIN(CARD_BIN,CARD_DIF, CARD_STATUS)
VALUES('111111', 'BSQ','02');   
INSERT INTO TBL_CARD_BIN(CARD_BIN,CARD_DIF, CARD_STATUS)
VALUES('12312312', 'QQC','03');
	
COMMIT
SELECT * FROM TBL_CARD_BIN         

SELECT count(*) FROM TBL_CARD_BIN WHERE CARD_BIN = 91234567
	
DROP TABLE TBL_CARD_BIN          

commit
         

	    INSERT 
	      INTO 
	  			TBL_TERM T
	    		(
	    		  T.TERM_NUM
	    		, T.BIS_NUM
	    		, T.TERM_OPEN_DATE
	    		, T.TERM_STATUS
	    		)
	    VALUES 
	    		(
	    		  9999999999
	    		 ,1234567899
	    		 ,11111101
	    		 ,01
	    		 )	 
	    		 
		SELECT 
			*
		FROM 
			TBL_TERM T
		WHERE 	
		TERM_NUM = '7000000007'

		ORDER BY TERM_NUM
